# Generated by Django 5.1.6 on 2025-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miqaat_registration',
            name='user',
        ),
        migrations.AddField(
            model_name='miqaat_registration',
            name='sabeel_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
