# Generated by Django 5.1.6 on 2025-03-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_rename_miqaat_miqaat_registration_miqaat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miqaat_registration',
            old_name='miqaat_id',
            new_name='miqaat',
        ),
    ]
